### ISSUE TITLE
Command "FE DD 00 FF" causes infinite loop

### ISSUE THREAD

**Issue by darconeous** [CanyonCasa/BackpackPlus#1]
The dump EEPROM command, when given a range of 0x00 to 0xFF, enters an infinite loop. It appears unable to recover without a reset.

**Comment by CanyonCasa** [comment]
Fixed by restricting page parameters to actual size of EEPROM. Technically, 0xFF exceeds available EEPROM pages for AT90USB162 that has 512 bytes. With the defined page size of 4 bytes, the page parameters need to be between 0 and 0x7F (512/4 -1).
